name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: 'Bugs Fixed'
    labels:
      - 'bug'
  - title: 'Hotfixes'
    labels:
      - 'hotfix'
  - title: 'Features Release'
    labels:
      - 'feature-new'
      - 'feature-enhancement'
  - title: 'Major Release'
    labels:
      - 'major'
change-template: '* $TITLE by @$AUTHOR in $URL'
change-title-escapes: '\<*_&'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  hotfix:
    labels:
      - 'hotfix'
  default: patch
template: |
  ## What's Changed
  $CHANGES
  
  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/commits/v$RESOLVED_VERSION
exclude-labels:
  - 'skip-changelog'
