name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: 'Bugs Fixed'
    labels:
      - 'bug'
      - 'fix'
      - 'bugfix'
  - title: 'Features Released'
    labels:
      - 'feature'
      - 'enhancement'
change-template: '* $TITLE by @$AUTHOR in $URL'
change-title-escapes: '\<*_&'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## What's Changed
  $CHANGES
  
  ## New Contributors
  $CONTRIBUTORS
  
  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/commits/$TAG_NAME
exclude-labels:
  - 'skip-changelog'
