name: Create Annotated Tag

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Add Tag Name'
        required: true
      tag_message:
        description: 'Add Tag Message'
        required: true

permissions:
  contents: write
  packages: read
  actions: read
  id-token: write

jobs:
  create-tag:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Ensure running on main branch
      run: |
        if [ "${{ github.ref }}" != "refs/heads/main" ]; then
          echo "This workflow must be run on the main branch."
          exit 1
        fi

    - name: Set up Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Fetch all tags
      run: git fetch --tags

    - name: Check if tag name is unique
      id: check_unique
      run: |
        TAG_NAME="v${{ github.event.inputs.tag_name }}"
        TAG_MESSAGE="${{ github.event.inputs.tag_message }}"
        TAG_MESSAGE_LOWER=$(echo "$TAG_MESSAGE" | tr '[:upper:]' '[:lower:]' | tr ' ' '-')

        # Check if tag name exists
        if git rev-parse "$TAG_NAME" >/dev/null 2>&1; then
          echo "Error: Tag name '$TAG_NAME' already exists."
          exit 1
        fi

    - name: Create annotated tag
      if: steps.check_unique.outcome == 'success'
      run: |
        TAG_NAME="v${{ github.event.inputs.tag_name }}"
        TAG_MESSAGE="${{ github.event.inputs.tag_message }}"
        TAG_MESSAGE_LOWER=$(echo "$TAG_MESSAGE" | tr '[:upper:]' '[:lower:]' | tr ' ' '-')
        git tag -a "$TAG_NAME" -m "$TAG_MESSAGE_LOWER"
        git push origin "$TAG_NAME"

    - name: Push changes to repository
      if: steps.check_unique.outcome == 'success'
      run: git push origin main
