name: Create Annotated Tag

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag Name'
        required: true
      tag_message:
        description: 'Tag Message'
        required: true

permissions:
  contents: write
  packages: read
  actions: read
  id-token: write

jobs:
  create-tag:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Create annotated tag
      run: |
        git tag -a "dev-${{ github.event.inputs.tag_name }}" -m "${{ github.event.inputs.tag_message }}"
        git push origin --tags

    - name: Push changes to repository
      run: git push origin main
