name: Create Annotated Tag

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag Name'
        required: true
      tag_message:
        description: 'Tag Message'
        required: true
      environment:
        type: choice
        description: 'Choose Environment'
        required: true
        options:
          - dev
          - test

permissions:
  contents: write
  packages: read
  actions: read
  id-token: write

jobs:
  create-tag:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Fetch all tags
      run: git fetch --tags

    - name: Check if tag name and message are unique
      id: check_unique
      run: |
        TAG_NAME="${{ github.event.inputs.environment }}-${{ github.event.inputs.tag_name }}"
        TAG_MESSAGE="${{ github.event.inputs.tag_message }}"

        # Check if tag name exists
        if git rev-parse "$TAG_NAME" >/dev/null 2>&1; then
          echo "Error: Tag name '$TAG_NAME' already exists."
          exit 1
        fi

        # Check if tag message exists
        for tag in $(git tag); do
          if [ "$(git for-each-ref refs/tags/$tag --format='%(contents)')" == "$TAG_MESSAGE" ]; then
            echo "Error: Tag message '$TAG_MESSAGE' is already in use."
            exit 1
          fi
        done

    - name: Create annotated tag
      if: steps.check_unique.outcome == 'success'
      run: |
        TAG_NAME="${{ github.event.inputs.environment }}-${{ github.event.inputs.tag_name }}"
        TAG_MESSAGE="${{ github.event.inputs.tag_message }}"
        git tag -a "$TAG_NAME" -m "$TAG_MESSAGE"
        git push origin "$TAG_NAME"

    - name: Push changes to repository
      if: steps.check_unique.outcome == 'success'
      run: git push origin main
