name: develop-to-release

on:
  workflow_dispatch:
    inputs:
      source_branch:
        description: 'Source branch to create new branch from'
        required: true
        default: 'main'
      new_branch_name:
        description: 'Name for the new branch'
        required: true

jobs:
  create_branch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create new branch
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout -b ${{ github.event.inputs.new_branch_name }} origin/${{ github.event.inputs.source_branch }}
          git push -u origin ${{ github.event.inputs.new_branch_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
