name: develop-to-release

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Type of release (major, minor, patch)'
        required: true
        default: 'patch'
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  create_release_branch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get the latest release tag
      id: get_latest_tag
      run: |
        latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
        echo "::set-output name=tag::$latest_tag"

    - name: Calculate new version
      id: calculate_version
      run: |
        release_type="${{ github.event.inputs.release_type }}"
        latest_tag="${{ steps.get_latest_tag.outputs.tag }}"

        if [ -z "$latest_tag" ]; then
          latest_tag="0.0.0"
        fi

        IFS='.' read -r -a version_parts <<< "$latest_tag"

        major=${version_parts[0]}
        minor=${version_parts[1]}
        patch=${version_parts[2]}

        if [ "$release_type" == "major" ]; then
          major=$((major + 1))
          minor=0
          patch=0
        elif [ "$release_type" == "minor" ]; then
          minor=$((minor + 1))
          patch=0
        elif [ "$release_type" == "patch" ]; then
          patch=$((patch + 1))
        fi

        new_version="$major.$minor.$patch"
        echo "::set-output name=new_version::$new_version"

    - name: Create new branch
      run: |
        new_version="${{ steps.calculate_version.outputs.new_version }}"
        git checkout -b release-$new_version
        git push origin release-$new_version
