name: Create Pull Request

on:
  workflow_dispatch:
    inputs:
      title:
        description: 'Pull Request Title'
        required: true
        default: 'Amazing new feature'
      body:
        description: 'Pull Request Body'
        required: true
        default: 'Please pull these awesome changes in!'
      head:
        description: 'Head Branch'
        required: true
        default: 'feature-branch'
      base:
        description: 'Base Branch'
        required: true
        default: 'main'

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Create Pull Request
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/pulls \
            -d '{
              "title":"${{ github.event.inputs.title }}",
              "body":"${{ github.event.inputs.body }}",
              "head":"${{ github.event.inputs.head }}",
              "base":"${{ github.event.inputs.base }}"
            }'
