name: rename-branch

on:
  workflow_dispatch:
    inputs:
      old_branch_name:
        description: 'Current branch name'
        required: true
      new_branch_name:
        description: 'New branch name'
        required: true

jobs:
  rename_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Rename branch
        run: |
          git branch -m "${{ github.event.inputs.old_branch_name }}" "${{ github.event.inputs.new_branch_name }}"
          git push origin -u "${{ github.event.inputs.new_branch_name }}"
          git push origin --delete "${{ github.event.inputs.old_branch_name }}"
