name: Create Production Tag

on:
  workflow_dispatch:

jobs:
  create_tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create and push tag
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag -a production-v3.0.16 -m "Production release v3.0.16"
          git push origin production-v3.0.16
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
