name: tag

on:
  workflow_dispatch:

jobs:
  create_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create and push tag
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag -a production-v3.0.16 -m "Production release v3.0.16"
          git push origin production-v3.0.16
