name: version-number-validator
on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release Type (major/minor/patch)'
        required: true
        type: choice
        options:
          - major
          - minor
          - patch
permissions:
  contents: write
  packages: read
  actions: read
  id-token: write
jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Ensure running on main branch
      run: |
        if [ "${{ github.ref }}" != "refs/heads/main" ]; then
          echo "This workflow must be run on the main branch."
          exit 1
        fi
    - name: Set up Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
    - name: Fetch all tags
      run: git fetch --tags
    - name: Generate new version
      id: generate_version
      run: |
        latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
        echo "Latest tag: $latest_tag"
        
        IFS='.' read -r major minor patch <<< "${latest_tag#v}"
        
        case "${{ github.event.inputs.release_type }}" in
          major)
            new_version="$((major + 1)).0.0"
            ;;
          minor)
            new_version="${major}.$((minor + 1)).0"
            ;;
          patch)
            new_version="${major}.${minor}.$((patch + 1))"
            ;;
          *)
            echo "Invalid release type"
            exit 1
            ;;
        esac
        
        echo "new_version=${new_version}" >> $GITHUB_OUTPUT
        echo "New version: v${new_version}"
    - name: Create and push tag
      run: |
        new_tag="v${{ steps.generate_version.outputs.new_version }}"
        git tag -a "$new_tag" -m "Release $new_tag"
        git push origin "$new_tag"
    - name: Push changes to repository
      run: git push origin main
